# Generated by Django 6.0.1 on 2026-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=8)),
                ('display_name', models.CharField(max_length=32)),
                ('contact_data', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('ip4', models.IntegerField()),
                ('settings_json', models.JSONField()),
                ('jwt_id', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
