# Generated by Django 6.0.1 on 2026-01-26 21:02
from django.core.management import call_command
from django.db import migrations
from django.contrib.auth import get_user_model

def load_fixture(apps, schema_editor):
    call_command('loaddata', 'user_data.json', app_label='users')


def reverse_load_fixture(apps, schema_editor):
    pass

def create_initial_data(apps, schema_editor):
    User = get_user_model()
    #User = apps.get_model('users', 'User')
    try:
        super_user = User.objects.get(pk=1)
        super_user.create_user_currency()
    except Exception as e:
        print(f"User 1 error {e}")

def reverse_initial_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_load_fixture),
        migrations.RunPython(create_initial_data, reverse_initial_data)
    ]
