# Generated by Django 6.0.1 on 2026-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_load_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ip4',
            field=models.IntegerField(null=True),
        ),
    ]
