"""
Django settings for thingbyb project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from utils.decrypt import DBCrypt

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

CAPTCHA_DIR = '/var/data/captcha'
CAPTCHA_PENDING_DIR = CAPTCHA_DIR + '/pending'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# TODO keep this secret like I do for the database and googleauth:
#    secret_db_pw = DBCrypt().decrypt('LZyBY1sWkFGnqwJjS0C/sw==')
SECRET_KEY = DBCrypt(
    keyfile=os.path.join('.keys', 'djsec.key')
).decrypt(
    "dO+efynMSoLL3y9jPrhhmXaTilC7nn+S2sCL"
    "TGES6fYdaexhUeqHtTK3X/STAKI3oWk7oxC5"
    "rZPW68CyuoP8K1eRr9JJTESzFwhIzJiN/kU="
)
#SECRET_KEY = 'django-insecure-fq!z&2wlzv))9$a#m(xefj%@kv+p86b!^33s&k046cy54b)8cx'

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

AUTH_USER_MODEL = 'users.User'

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'users.apps.UsersConfig',
    'activities.apps.ActivitiesConfig',
    'posts.apps.PostsConfig',
    'trading.apps.TradingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'thingbyb.urls'

GLOBAL_FILES = {
    'css_files':[
        'css/jquery-ui.structure.min.css', 
        'css/jquery-ui.theme.min.css', 
        'css/form.css', 
        'css/fonts.css', 
        'css/layout.css', 
        'css/bs.css',
        'css/channels.css'
    ],
    'js_files':[
        'js/jquery.min.js', 
        'js/jquery-ui.min.js',
        'js/bs.js',
        'js/LoginPanel.js',
        'js/channels.js'
    ],
    'icons':{
        'trading':'Paper Trading',
        'running':'ByBGrid Demo (Running)',
        'code':'Code',
        'reactjs':'React',
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR), 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'thingbyb.context_processors.global_vars'
            ],
        },
    },
]

WSGI_APPLICATION = 'thingbyb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
secret_db_pw = DBCrypt().decrypt('LZyBY1sWkFGnqwJjS0C/sw==')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'thingbyb_django',
        'USER': 'bs',
        'PASSWORD': secret_db_pw,
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': 'SET default_storage_engine=INNODB',
        }
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

FIXTURE_DIRS = [
    os.path.join(BASE_DIR, 'fixtures')
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'users.backends.UserBackend',
]

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

#AUTH_PASSWORD_VALIDATORS = [
#    {
#        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#    },
#    {
#        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#    },
#]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
