# Generated by Django 6.0.1 on 2026-01-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RN', 'Running')], default='RN', max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('time', models.TimeField()),
                ('heart_rate', models.IntegerField()),
                ('avg_pace', models.CharField(max_length=5)),
                ('best_pace', models.CharField(max_length=5)),
                ('ascent', models.IntegerField()),
                ('descent', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
    ]
